### ISSUE TITLE
The built in composed text input key sequences don't include 'ta' for TAB

### ISSUE THREAD

**Issue by siebenmann** [deadpixi/sam#12]
Commits 3ca56f0a42652edc827cdcfaad1c66a39b100587 and ecca4beef4309c4d78aef083f22f9c8fdb3b29be updated doc/sam.1 and doc/keyboard to document and include the new 'ta' sequence to insert a hard tab even if -e is making the tab key insert spaces. However, libXg/latin1.c hasn't been updated to include this sequence, so it doesn't work without a `$HOME/.keyboard` file with the sequence in it (including a plain copy of the default one).

(As a larger issue, the same information is now in three places that must be manually kept in synchronization: in the manpage, in the example keyboard file, and in the source code itself. Would it make sense to ship auxiliary scripts to generate all of this from a master source, even if they're only run by hand instead of as part of the normal build process?)

**Comment by deadpixi** [comment]
I've reworked the code for reading the keyboard file so that composition sequences are overridden/added, rather than replacing the default table outright. That means that the default sequences are always available unless explicitly overridden.

@siebenmann I also added a key binding using the new keyboard code such that Ctrl-Tab (check commands.h) inserts a raw tab even with tab expansion enabled.

Also, I split the documentation for the keyboard file into a separate man page; this makes things a bit cleaner. Finally, I made the example keyboard file a random sampling, so that it's not expected to be complete (and doesn't need to be with the new default-honoring code).

I'm going to close this issue; please open a new one if there's still a problem. Thanks!
